export const LOAD_USERS_PENDING = "LOAD_USERS_PENDING";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";
export const CHANGE_USERS_PAGE = "CHANGE_USERS_PAGE";
export const CAPTURE_SEARCH_TERM = "CAPTURE_SEARCH_TERM";
export const NEW_SEARCH_SUCCESS = "NEW_SEARCH_SUCCESS";
