export const LOAD_COLLECTIONS_PENDING = "LOAD_PHOTOS_PENDING";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_COLLECTIONS_ERROR = "LOAD_PHOTOS_ERROR";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CAPTURE_SEARCH_TERM = "CAPTURE_SEARCH_TERM";
export const NEW_SEARCH_SUCCESS = "NEW_SEARCH_SUCCESS";
