export const LOAD_PHOTOS_PENDING = "_PHOTOS_PENDING";
export const LOAD_HOME_PHOTOS_SUCCESS = "LOAD_HOME_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_ERROR = "LOAD_PHOTOS_ERROR";
export const CHANGE_PAGE = "CHANGE_HOME_PAGE";
