export const LOAD_PROFILE_PENDING = "LOAD_PROFILE_PENDING";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";
export const LOAD_USER_PHOTOS_SUCCESS = "LOAD_USER_PHOTOS_SUCCESS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CAPTURE_USERNAME = "CAPTURE_USERNAME";
export const CLEAR_PHOTOS = "CLEAR_PHOTOS";
