export const OPEN_PHOTO = "OPEN_PHOTO";
export const CLOSE_PHOTO = "CLOSE_PHOTO";
export const CLICK_NEXT_PHOTO = "CLICK_NEXT_PHOTO";
export const CLICK_PREVIOUS_PHOTO = "CLICK_PREVIOUS_PHOTO";
export const COLLECT_PHOTO_ARRAY = "COLLECT_PHOTO_ARRAY";
