export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_PENDING = "LOAD_PHOTOS_PENDING";
export const LOAD_PHOTOS_ERROR = "LOAD_PHOTOS_ERROR";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const LOAD_MORE_PHOTOS_SUCCESS = "LOAD_MORE_PHOTOS_SUCCESS";
export const LOAD_MORE_PHOTOS_PENDING = "LOAD_MORE_PHOTOS_PENDING";
export const LOAD_MORE_PHOTOS_ERROR = "LOAD_MORE_PHOTOS_ERROR";
