export const LOAD_COLLECTION_PENDING = "LOAD_COLLECTION_PENDING";
export const LOAD_COLLECTION_DATA_SUCCESS = "LOAD_COLLECTION_DATA_SUCCESS";
export const LOAD_COLLECTION_PHOTOS_SUCCESS = "LOAD_COLLECTION_PHOTOS_SUCCESS";
export const LOAD_COLLECTION_ERROR = "LOAD_COLLECTION_ERROR";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const COLLECT_ID = "COLLECT_ID";
export const CLEAR_PHOTOS = "CLEAR_PHOTOS";
